#!/usr/bin/env node

var MODULE_REQUIRE
	/* in-package */
	, logger = require('../util/logger')
	, runner = require('../util/runner')
	, OPTIONS = require('../util/options')
	;

// ---------------------------
// 检查系统命令。
var cmd, response;

response = runner('npm publish');
if (response.error) {
	logger.error('Failed to publish to NPM registry.');
	process.exit(1);
}
logger.info('Published to NPM repository.');
